// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔐 CORREÇÃO CRÍTICA: Usar APENAS variáveis de ambiente
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validação de configuração
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('🚨 ERRO: Variáveis de ambiente do Supabase não configuradas');
  console.error('📋 Necessário configurar:');
  console.error('  - VITE_SUPABASE_URL');
  console.error('  - VITE_SUPABASE_ANON_KEY');
  throw new Error('Configuração do Supabase inválida. Verifique as variáveis de ambiente no arquivo .env.local');
}

console.log('✅ Supabase configurado via variáveis de ambiente');
console.log('🔗 URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  }
  // 🔧 CORREÇÃO: Removido headers customizados que causavam erro CORS
});

// 🔧 Health check do cliente (simplificado)
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('base_contracts').select('id').limit(1);
    if (error && error.code !== 'PGRST301') { // Ignorar erro de tabela vazia
      throw error;
    }
    console.log('✅ Conexão com Supabase OK');
    return true;
  } catch (error) {
    console.error('❌ Erro de conexão com Supabase:', error);
    return false;
  }
};

// 🔧 NOVO: Function para testar Edge Function
export const checkEdgeFunctionHealth = async () => {
  try {
    const response = await fetch(`${SUPABASE_URL}/functions/v1/analyze-contract`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ test: true })
    });
    
    console.log('🔧 Edge Function Response Status:', response.status);
    return response.status === 200 || response.status === 400; // 400 é ok para teste
  } catch (error) {
    console.error('❌ Edge Function não disponível:', error);
    return false;
  }
};

// 🔧 NOVO: Health check completo do sistema
export const performSystemHealthCheck = async () => {
  console.log('🏥 Iniciando health check completo...');
  
  const checks = {
    supabaseConnection: false,
    edgeFunction: false
  };
  
  // Testar conexão com Supabase
  checks.supabaseConnection = await checkSupabaseConnection();
  
  // Testar Edge Function
  checks.edgeFunction = await checkEdgeFunctionHealth();
  
  console.log('📊 Resultado do health check:', checks);
  
  return checks;
};
