// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔐 CONFIGURAÇÃO DIRETA: Usando credenciais do projeto Supabase
const SUPABASE_URL = 'https://kwwqyfvkpjatckvngtur.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3d3F5ZnZrcGphdGNrdm5ndHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODk2NzAsImV4cCI6MjA2NjM2NTY3MH0.DE84x3wpGTDKIc4VCaOHQUI5hj76OWqC2Vk7tzKpYEA';

console.log('✅ Supabase configurado via variáveis de ambiente');
console.log('🔗 URL:', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  db: {
    schema: 'public'
  }
  // 🔧 CORREÇÃO: Removido headers customizados que causavam erro CORS
});

// 🔧 Health check do cliente (simplificado)
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('base_contracts').select('id').limit(1);
    if (error && error.code !== 'PGRST301') { // Ignorar erro de tabela vazia
      throw error;
    }
    console.log('✅ Conexão com Supabase OK');
    return true;
  } catch (error) {
    console.error('❌ Erro de conexão com Supabase:', error);
    return false;
  }
};

// 🔧 NOVO: Function para testar Edge Function
export const checkEdgeFunctionHealth = async () => {
  try {
    const response = await fetch(`${SUPABASE_URL}/functions/v1/analyze-contract`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ test: true })
    });
    
    console.log('🔧 Edge Function Response Status:', response.status);
    return response.status === 200 || response.status === 400; // 400 é ok para teste
  } catch (error) {
    console.error('❌ Edge Function não disponível:', error);
    return false;
  }
};

// 🔧 NOVO: Health check completo do sistema
export const performSystemHealthCheck = async () => {
  console.log('🏥 Iniciando health check completo...');
  
  const checks = {
    supabaseConnection: false,
    edgeFunction: false
  };
  
  // Testar conexão com Supabase
  checks.supabaseConnection = await checkSupabaseConnection();
  
  // Testar Edge Function
  checks.edgeFunction = await checkEdgeFunctionHealth();
  
  console.log('📊 Resultado do health check:', checks);
  
  return checks;
};
